---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mockservice
  name: mockservice
  namespace: alpha-issuer-system
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: mockservice
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mockservice
  name: mockservice
  namespace: alpha-issuer-system
spec:
  containers:
  - image: ptgdit/alpha-issuer.io/mockservice:latest
    imagePullPolicy: IfNotPresent
    name: mockservice
